name: PackAndPublish
defaults:
  run:
    working-directory: src

on:
  release: 
    types: [published]
    
jobs:
  PackAndPublish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${GITHUB_REF} /p:InformationalVersion=${GITHUB_SHA}
    - name: Push
      env:
        nuget_api_key: ${{ secrets.NUGET_TOKEN }}
      run: dotnet nuget push "./Knuth.Authentication.TOTP/bin/Release/Knuth.Authentication.TOTP.${GITHUB_REF}.nupkg" --api-key "${nuget_api_key}"
